### ISSUE TITLE
Lein cucumber and the cucumber-jvm included lein plugin

### ISSUE THREAD

**Issue by rplevy-draker** [nilswloka/lein-cucumber#6]
Hi Nils,

This is a topic for discussion more so than an issue, but I think it will turn into an issue depending on the answer, and we can just edit the topic.

I noticed that the code initiated by @hiredman that you brought to completion on the cucumber-jvm project includes its own lein plugin.  But there might be reasons to continue developing your plugin separately.  For example, pushing releases to clojars more rapidly than the release of cucumber-jvm out to maven central.

So, what do you think: should the features of your plugin (for example, the configurability of feature path that I added recently) be included in the plugin in cucumber-jvm, or should that plugin be left as an alternative (or deleted from the cucumber-jvm source?)

Rob

**Comment by nilswloka** [comment]
Hello Rob,

I'd prefer having separate release cycles for cucumber-jvm and lein-cucumber for the reasons you mentioned. Whether lein-cucumber should be used instead of the "internal" plugin is a question that should probably be answered by the cucumber-jvm team. If so, then the best thing to do IMHO would be to:
1. Update and release lein-cucumber to use the latest version of cucumber-jvm
2. Update the example (https://github.com/cucumber/cucumber-jvm/tree/master/examples/clojure_cukes) to use lein- cucumber (and the new syntax, but that's a different issue)
3. Remove the internal plugin from cucumber-jvm

Nils

**Comment by rplevy-draker** [comment]
That's exactly how I feel about it as well.  Assuming no words from @hiredman on the matter, let's delete the lein plugin part of that code.

**Comment by nilswloka** [comment]
Just had a look at https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/runtime/Runtime.java. Getting lein-cucumber to work with the new Runtime signature will most likely require a complete rewrite. I'm going to think about a possible design. Any ideas are welcome.

Update: Most likely, something analogous to https://github.com/cucumber/cucumber-jvm/tree/master/junit is required.

**Comment by nilswloka** [comment]
Just added a branch with an updated version:
https://github.com/nilswloka/lein-cucumber/tree/1.0.0 works with RC23 of cucumber-jvm and leiningen 2. It's probably not backwards compatible with leiningen 1

**Comment by rplevy-draker** [comment]
This is great!  Would you push the snapshot to clojars?

**Comment by rplevy-draker** [comment]
This works great by the way, tabular data feature is great to have.  This also forced me to move to lein 2 which is good. :)

**Comment by nilswloka** [comment]
Will push 1.0.0 to clojars after adding a liitle more test coverage this week.
